name: Create Zip Archives

on: [workflow_dispatch, push]

jobs:
  create-zips:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - run: |
        pip install pandas requests
        python download_zips.py
    
    - uses: actions/upload-artifact@v4
      with:
        name: zip-files
        path: |
          PRIMARY.zip
          Secondary_Higher_Secondary.zip
