name: My Watch List

on:
  schedule:
    - cron: '*/15 2-8 * * 1-5'
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'Who triggered this workflow'
        required: false
        default: 'manual'
      timestamp:
        description: 'Trigger timestamp'
        required: false

jobs:
  update-csv:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        script: 
          - fetch_and_save.py
          - nifty50_top10.py
          - etf_fetch.py
          - global_data.py
          - global_commodity.py
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python with CACHE
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python Scripts/${{ matrix.script }}
  
  commit-and-push:
    runs-on: ubuntu-latest
    needs: update-csv
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Data/nse_all_indices.csv Data/nifty50_stocks_top10.csv Data/etf.csv Data/GLOBAL_DATA.csv Data/GLOBAL_COMMODITIES.csv
          git diff --staged --quiet || (git commit -m "Auto update $(date)" && git push)
